plugins {
    id "com.android.library"
    id "com.vanniktech.maven.publish"
}

def argArtifactName = System.getenv('ARG_ARTIFACT_NAME') ?: 'ffmpeg-kit-main-16kb'
def argVersionName = System.getenv('ARG_VERSIOM_NAME') ?: '6.1.4'
def argVersionCode = Integer.valueOf(System.env.ARG_VERSIOM_CODE ?: 60104)

android {
    if (project.android.hasProperty("namespace")) {
        namespace 'com.arthenica.ffmpegkit'
    }
    compileSdk 35
    ndkVersion "27.0.12077973"

    defaultConfig {
        minSdk 24
        targetSdk 35
        versionCode argVersionCode
        versionName "$argVersionName"
        project.archivesBaseName = "ffmpeg-kit"
        consumerProguardFiles "consumer-rules.pro"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }

    sourceSets {
        main {
            jniLibs.srcDirs = ["../libs"]
        }
    }

    testOptions {
        unitTests.returnDefaultValues = true
        unitTests.all {
            systemProperty 'enable.ffmpeg.kit.test.mode', 'true'
        }
    }


    // publishing {
    //     singleVariant('release') {
    //         withJavadocJar()
    //         withSourcesJar()
    //     }
    // }
}

task javadoc(type: Javadoc) {
    title = 'FFmpegKit'
    destinationDir = file("${projectDir}/../../docs/android/javadoc")
    classpath += project.files(android.getBootClasspath().join(File.pathSeparator))
    source = android.sourceSets.main.java.srcDirs
    configurations.implementation.setCanBeResolved(true)
    classpath += configurations.implementation
}

dependencies {
    implementation 'com.arthenica:smart-exception-java:0.2.1'
    testImplementation "androidx.test.ext:junit:1.1.5"
    testImplementation 'org.json:json:20230618'
}

mavenPublishing {
    publishToMavenCentral()
    if (System.getenv('ORG_GRADLE_PROJECT_SIGNINGINMEMORYKEYID')) {
        signAllPublications()
    }

    coordinates("io.github.jamaismagic.ffmpeg", "$argArtifactName", "$argVersionName")


    pom {
        name = "FFMPEG Android 16KB"
        description = "FFmpeg Kit for Android (Maven Package for https://github.com/JamaisMagic/ffmpeg-kit-16KB)."
        inceptionYear = "2025"
        url = "https://github.com/JamaisMagic/ffmpeg-kit-16KB"
        licenses {
            license {
                name = "GNU LESSER GENERAL PUBLIC LICENSE Version 3"
                url = "https://www.gnu.org/licenses/lgpl-3.0.txt"
                distribution = "https://www.gnu.org/licenses/lgpl-3.0.txt"
            }
        }
        developers {
            developer {
                id = "JamaisMagic"
                name = "JamaisNg"
                url = "https://github.com/JamaisMagic"
            }
        }
        scm {
            url = "https://github.com/JamaisMagic/ffmpeg-kit-16KB"
            connection = "scm:git@github.com:JamaisMagic/ffmpeg-kit-16KB.git"
            developerConnection = "=scm:git@github.com:JamaisMagic/ffmpeg-kit-16KB.git"
        }
    }
}

afterEvaluate {
    tasks.matching { it.name == 'publishToMavenCentral' }.configureEach {
        onlyIf { System.getenv('ORG_GRADLE_PROJECT_mavenCentralUsername') }
    }

    if (System.getenv('GITHUB_TOKEN')) {
        publishing.repositories {
            maven {
                name = "GitHubPackages"
                url = uri("https://maven.pkg.github.com/${System.getenv('GITHUB_REPOSITORY')}")
                credentials {
                    username = System.getenv('GITHUB_ACTOR')
                    password = System.getenv('GITHUB_TOKEN')
                }
            }
        }
    }
}
