name: android build scripts audio

on:
  workflow_dispatch:

jobs:
  build-main-on-linux:
    name: android main audio on linux (ndk-r27-16k)
    runs-on: ubuntu-24.04
    timeout-minutes: 1440
    defaults:
      run:
        shell: bash
    env:
      ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.ORG_GRADLE_PROJECT_mavenCentralUsername }}
      ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.ORG_GRADLE_PROJECT_mavenCentralPassword }}
      ORG_GRADLE_PROJECT_SIGNINGINMEMORYKEYID: ${{ secrets.ORG_GRADLE_PROJECT_SIGNINGINMEMORYKEYID }}
      ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.ORG_GRADLE_PROJECT_signingInMemoryKey }}
      ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{ secrets.ORG_GRADLE_PROJECT_signingInMemoryKeyPassword }}
      ARG_ARTIFACT_NAME: 'ffmpeg-kit-main-audio-16kb'
      ARG_VERSIOM_NAME: '6.1.7'
      ARG_VERSIOM_CODE: 60107
    steps:
      - uses: actions/checkout@v4
      - name: set up build tools
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends build-essential gperf groff meson autoconf automake autogen gnulib gettext gtk-doc-tools gnutls-bin libgnutls28-dev libssl-dev dash git-core libtool autopoint libavutil-dev libv4l-dev python3 nettle-dev libp11-kit-dev libtspi-dev libunistring-dev libtasn1-bin libtasn1-6-dev libidn2-0-dev gawk libtss2-dev libunbound-dev dns-root-data bison texinfo texlive texlive-plain-generic texlive-extra-utils libfreetype6-dev libglib2.0-dev libcairo2-dev ragel pkg-config nasm yasm ninja-build
          sudo apt-get install -y --no-install-recommends gcc-14
          sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-14 100
          echo "OPENSSL_ROOT_DIR=/usr/include/openssl" >> $GITHUB_ENV
          wget -q https://github.com/Kitware/CMake/releases/download/v3.31.8/cmake-3.31.8-linux-x86_64.tar.gz -O cmake.tar.gz
          tar -xzf cmake.tar.gz
          mkdir -p .cmake
          mv cmake-3.31.8-linux-x86_64 .cmake/
          echo "$PWD/.cmake/cmake-3.31.8-linux-x86_64/bin" >> $GITHUB_PATH
          echo "PATH=$PWD/.cmake/cmake-3.31.8-linux-x86_64/bin:$PATH" >> $GITHUB_ENV
          ./.cmake/cmake-3.31.8-linux-x86_64/bin/cmake --version
          gcc --version
      - name: set up adopt jdk 17
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '17'
      - name: prerequisites
        run: ${ANDROID_HOME}/cmdline-tools/latest/bin/sdkmanager --uninstall "cmake;3.10.2.4988404" "cmake;3.18.1"
      - name: set up android ndk r27 (16k support)
        run: |
          curl -L -s "https://dl.google.com/android/repository/android-ndk-r27d-linux.zip" -o ndk.zip
          unzip -q -o ndk.zip -d .ndk
          echo "ANDROID_NDK_ROOT=$PWD/.ndk/$(ls .ndk)" >> $GITHUB_ENV
      - name: run the build script
        run: ./android.sh --disable-arm-v7a --enable-android-media-codec --enable-android-zlib --enable-lame --enable-libilbc --enable-libvorbis --enable-opencore-amr --enable-opus --enable-shine --enable-soxr --enable-speex --enable-twolame --enable-vo-amrwbenc
      - name: prepare and upload main aar
        run: |
          AAR_PATH=$(find prebuilt -type f -name 'ffmpeg-kit.aar')
          if [ -z "$AAR_PATH" ]; then
            echo "Error: ffmpeg-kit.aar not found in prebuilt directory."
            exit 1
          fi
          mv "$AAR_PATH" "ffmpeg-kit-main-audio-ndk-r27-16k.aar"
      - uses: actions/upload-artifact@v4
        with:
          name: ffmpeg-kit-main-audio-aar
          path: ffmpeg-kit-main-audio-ndk-r27-16k.aar
          if-no-files-found: error
      - name: print build logs
        if: ${{ always() }}
        run: cat build.log
      - name: print ffbuild logs
        if: ${{ failure() }}
        run: '[[ -f ./src/ffmpeg/ffbuild/config.log ]] && tail -1000 ./src/ffmpeg/ffbuild/config.log'

  build-lts-on-linux:
    name: android lts audio on linux (ndk-r27-16k)
    runs-on: ubuntu-24.04
    timeout-minutes: 1440
    defaults:
      run:
        shell: bash
    env:
      ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.ORG_GRADLE_PROJECT_mavenCentralUsername }}
      ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.ORG_GRADLE_PROJECT_mavenCentralPassword }}
      ORG_GRADLE_PROJECT_SIGNINGINMEMORYKEYID: ${{ secrets.ORG_GRADLE_PROJECT_SIGNINGINMEMORYKEYID }}
      ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.ORG_GRADLE_PROJECT_signingInMemoryKey }}
      ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{ secrets.ORG_GRADLE_PROJECT_signingInMemoryKeyPassword }}
      ARG_ARTIFACT_NAME: 'ffmpeg-kit-lts-audio-16kb'
      ARG_VERSIOM_NAME: '6.1.7'
      ARG_VERSIOM_CODE: 60107
    steps:
      - uses: actions/checkout@v4
      - name: set up build tools
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends build-essential gperf groff meson autoconf automake autogen gnulib gettext gtk-doc-tools gnutls-bin libgnutls28-dev libssl-dev dash git-core libtool autopoint libavutil-dev libv4l-dev python3 nettle-dev libp11-kit-dev libtspi-dev libunistring-dev libtasn1-bin libtasn1-6-dev libidn2-0-dev gawk libtss2-dev libunbound-dev dns-root-data bison texinfo texlive texlive-plain-generic texlive-extra-utils libfreetype6-dev libglib2.0-dev libcairo2-dev ragel pkg-config nasm yasm ninja-build
          sudo apt-get install -y --no-install-recommends gcc-14
          sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-14 100
          echo "OPENSSL_ROOT_DIR=/usr/include/openssl" >> $GITHUB_ENV
          wget -q https://github.com/Kitware/CMake/releases/download/v3.31.8/cmake-3.31.8-linux-x86_64.tar.gz -O cmake.tar.gz
          tar -xzf cmake.tar.gz
          mkdir -p .cmake
          mv cmake-3.31.8-linux-x86_64 .cmake/
          echo "$PWD/.cmake/cmake-3.31.8-linux-x86_64/bin" >> $GITHUB_PATH
          echo "PATH=$PWD/.cmake/cmake-3.31.8-linux-x86_64/bin:$PATH" >> $GITHUB_ENV
          ./.cmake/cmake-3.31.8-linux-x86_64/bin/cmake --version
          gcc --version
      - name: set up adopt jdk 17
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '17'
      - name: prerequisites
        run: ${ANDROID_HOME}/cmdline-tools/latest/bin/sdkmanager --uninstall "cmake;3.10.2.4988404" "cmake;3.18.1"
      - name: set up android ndk r27 (16k support)
        run: |
          curl -L -s "https://dl.google.com/android/repository/android-ndk-r27d-linux.zip" -o ndk.zip
          unzip -q -o ndk.zip -d .ndk
          echo "ANDROID_NDK_ROOT=$PWD/.ndk/$(ls .ndk)" >> $GITHUB_ENV
      - name: run the build script
        run: ./android.sh --lts --disable-arm-v7a --enable-android-media-codec --enable-android-zlib --enable-lame --enable-libilbc --enable-libvorbis --enable-opencore-amr --enable-opus --enable-shine --enable-soxr --enable-speex --enable-twolame --enable-vo-amrwbenc
      - name: prepare and upload lts aar
        run: |
          AAR_PATH=$(find prebuilt -type f -name 'ffmpeg-kit.aar')
          if [ -z "$AAR_PATH" ]; then
            echo "Error: ffmpeg-kit.aar not found in prebuilt directory."
            exit 1
          fi
          mv "$AAR_PATH" "ffmpeg-kit-lts-audio-ndk-r27-16k.aar"
      - uses: actions/upload-artifact@v4
        with:
          name: ffmpeg-kit-lts-audio-aar
          path: ffmpeg-kit-lts-audio-ndk-r27-16k.aar
          if-no-files-found: error
      - name: print build logs
        if: ${{ always() }}
        run: cat build.log
      - name: print ffbuild logs
        if: ${{ failure() }}
        run: '[[ -f ./src/ffmpeg/ffbuild/config.log ]] && tail -1000 ./src/ffmpeg/ffbuild/config.log'

  create-release:
    name: create github release
    needs: [build-main-on-linux, build-lts-on-linux]
    runs-on: ubuntu-24.04
    if: github.event_name == 'workflow_dispatch'
    permissions:
      contents: write
    steps:
      - name: set release tag
        id: set_tag
        run: echo "TAG_NAME=ffmpeg-kit-android-audio-$(date +'%Y-%m-%dT%H-%M-%S')" >> $GITHUB_ENV
      - name: download all aar artifacts
        uses: actions/download-artifact@v4
        with:
          path: aar-artifacts
      - name: list downloaded files for debug
        run: ls -R aar-artifacts
      - name: create github release and upload assets
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.TAG_NAME }}
          name: "Android AARs Audio (NDK r27-16k) - ${{ env.TAG_NAME }}"
          body: "Automated release of Android AAR files (audio variant) from Linux builds using NDK r27 with 16kB page size support."
          prerelease: true
          files: aar-artifacts/*/*.aar
